spring:
  application:
    name: sl-main-service

springdoc:
  swagger-ui:
    url: /api/api.yaml

dynamodb:
  endpoint: http://localhost:8000
  tableName: SLTable

aws:
  region: us-east-1
  accessKeyId: fakeKeyId
  secretKey: fakeKey

cors:
  trustOrigin: http://localhost:5173

constants:
  units:
    - g
    - kg
    - ml
    - l
    - pieces
    - spoons
    - teaspoons

  categories:
    - Vegetables & Fruits
    - Bread
    - Dairy & Eggs
    - Beverages
    - Pantry / Dry Goods
    - Personal Care
    - Cleaning
    - Snacks
    - Other
    - Spices
    - Meat