openapi: 3.1.0
info:
  title: Shopping List Main Service
  version: 1.0.0

paths:

  /shoppingLists/{userId}:
    $ref: "paths/shoppingLists.yaml#/shoppingListsForUser"

  /recipes/{userId}:
    $ref: "paths/recipes.yaml#/recipesForUser"

  /units:
    $ref: "paths/units.yaml#/units"

  /categories:
    $ref: "paths/categories.yaml#/categories"

components:
  schemas:

    shoppingList:
      $ref: "schemas/shoppingLists.yaml#/shoppingList"
    recipe:
      $ref: "schemas/recipes.yaml#/recipe"

  responses:
    forbidden:
      $ref: "responses/responses.yaml#/forbidden"
    notFound:
      $ref: "responses/responses.yaml#/notFound"

