openapi: 3.1.0
info:
  title: Shopping List Main Service
  version: 1.0.0

paths:

  /v1/shoppingLists/{userId}:
    get:
      operationId: getShoppingListForUser
      summary: Retrieve all shopping lists for user.
      description: Retrieve all shopping lists that were created by specified user.
      tags:
        - ShoppingLists
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:

        "200":
          description: Everything went fine
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/shoppingList"

        "403":
          $ref: "#/components/responses/forbidden"

        "404":
          $ref: "#/components/responses/notFound"


  /v1/recipes/{userId}:
    get:
      operationId: getRecipesForUser
      summary: Retrieve all recipes for user.
      description: Retrieve all recipes that were created by specified user.
      tags:
        - Recipes
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:

        "200":
          description: Everything went fine
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/recipe"

        "403":
          $ref: "#/components/responses/forbidden"

        "404":
          $ref: "#/components/responses/notFound"

  /v1/units:
    get:
      operationId: getAllUnits
      tags:
        - Units
      summary: Retrieve all units.
      responses:

        "200":
          description: Everything went fine
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string


  /v1/categories:
    get:
      operationId: getAllCategories
      tags:
        - Categories
      summary: Retrieve all categories.
      responses:

        "200":
          description: Everything went fine
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:

  schemas:
    shoppingList:
      $ref: "schemas/shoppingLists.yaml#/shoppingList"
    recipe:
      $ref: "schemas/recipes.yaml#/recipe"

  responses:
    forbidden:
      $ref: "responses/responses.yaml#/forbidden"
    notFound:
      $ref: "responses/responses.yaml#/notFound"

